name: Daemon CI/CD

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - daemon/**
      - .github/workflows/daemon-linode.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - daemon/**
      - .github/workflows/daemon-linode.yml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3

      - name: Build
        run: cd daemon && go build .
